age = int(input("Please tell me your age: "))
print(f"You are currently {18} years old.")
print(f"In 10 years, you will be {age + 10}.")
print(f"In 20 years, you will be {age + 20}.")
print(f"In 30 years, you will be {age + 30}.")